apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: profiles-kfam
spec:
  action: ALLOW
  selector:
    matchLabels:
      app.kubernetes.io/name: profiles-controller-manager
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/kubeflow/sa/centraldashboard
              - cluster.local/ns/kubeflow/sa/waypoint
