apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../base
- service.yaml
- authorizationpolicy.yaml

labels:
  - pairs:
      kustomize.component: profiles

patches:
- path: patches/kfam.yaml
- path: patches/remove-namespace.yaml


images:
- name: ghcr.io/kubeflow/kubeflow/kfam
  newName: ghcr.io/kubeflow/kubeflow/kfam
  newTag: v1.10.0
- name: ghcr.io/kubeflow/kubeflow/profile-controller
  newName: ghcr.io/mvnsolutions/kubeflow/profile-controller
  newTag: v1.10.0