apiVersion: v1
kind: Service
metadata:
  name: profiles-kfam
spec:
  selector:
    app.kubernetes.io/instance: profiles-controller-manager
    app.kubernetes.io/name: profiles-controller-manager
  ports:
    - protocol: TCP
      targetPort: 8081
      port: 8081
      appProtocol: http
